// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Message for importing data to Lustre.
public struct ImportDataRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The name of the Managed Lustre instance in the format
  /// `projects/{project}/locations/{location}/instances/{instance}`.
  public var name: Swift.String = Swift.String()

  /// Optional. UUID to identify requests.
  public var requestId: Swift.String = Swift.String()

  /// Optional. User-specified service account used to perform the transfer.
  /// If unspecified, the default Managed Lustre service agent will be used.
  public var serviceAccount: Swift.String = Swift.String()

  /// A Cloud Storage URI of a folder to import file data from, in the
  /// form of `gs://<bucket_name>/<path_inside_bucket>/`.
  public var source: OneOf_Source? = nil

  /// The destination of the data transfer.
  public var destination: OneOf_Destination? = nil

  /// Initialize a new instance of `ImportDataRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ImportDataRequest().with { $0.gcsPath = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case gcsPath = "gcsPath"
    case lustrePath = "lustrePath"
    case name = "name"
    case requestId = "requestId"
    case serviceAccount = "serviceAccount"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.requestId = try container.decode(Swift.String.self, forKey: .requestId)
    self.serviceAccount = try container.decode(Swift.String.self, forKey: .serviceAccount)

    var source: OneOf_Source? = nil
    let sourceCheckAndSet = {
      if source != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'source'"))
      }
      source = $0
    }
    if let gcsPath = try container.decodeIfPresent(GcsPath?.self, forKey: .gcsPath) {
      try sourceCheckAndSet(.gcsPath(gcsPath))
    }
    self.source = source

    var destination: OneOf_Destination? = nil
    let destinationCheckAndSet = {
      if destination != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'destination'"))
      }
      destination = $0
    }
    if let lustrePath = try container.decodeIfPresent(LustrePath?.self, forKey: .lustrePath) {
      try destinationCheckAndSet(.lustrePath(lustrePath))
    }
    self.destination = destination
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.requestId, forKey: .requestId)
    try container.encode(self.serviceAccount, forKey: .serviceAccount)

    if let choice = self.source {
      switch choice {
      case .gcsPath(let value):
        try container.encode(value, forKey: .gcsPath)
      }
    }

    if let choice = self.destination {
      switch choice {
      case .lustrePath(let value):
        try container.encode(value, forKey: .lustrePath)
      }
    }
  }

  /// A Cloud Storage URI of a folder to import file data from, in the
  /// form of `gs://<bucket_name>/<path_inside_bucket>/`.
  public enum OneOf_Source: Codable, Equatable, Sendable {
    /// The Cloud Storage source bucket and, optionally, path inside the bucket.
    /// If a path inside the bucket is specified, it must end with a forward
    /// slash (`/`).
    indirect case gcsPath(GcsPath?)
  }

  /// The destination of the data transfer.
  public enum OneOf_Destination: Codable, Equatable, Sendable {
    /// Lustre path destination.
    indirect case lustrePath(LustrePath?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.lustre.v1.ImportDataRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
