// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A Managed Lustre instance.
public struct Instance: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. The name of the instance.
  public var name: Swift.String = Swift.String()

  /// Required. Immutable. The filesystem name for this instance. This name is
  /// used by client-side tools, including when mounting the instance. Must be
  /// eight characters or less and can only contain letters and numbers.
  public var filesystem: Swift.String = Swift.String()

  /// Required. The storage capacity of the instance in gibibytes (GiB). Allowed
  /// values are from `18000` to `954000`, in increments of 9000.
  public var capacityGib: Swift.Int64 = Swift.Int64()

  /// Required. Immutable. The full name of the VPC network to which the instance
  /// is connected. Must be in the format
  /// `projects/{project_id}/global/networks/{network_name}`.
  public var network: Swift.String = Swift.String()

  /// Output only. The state of the instance.
  public var state: Instance.State = Instance.State()

  /// Output only. Mount point of the instance in the format
  /// `IP_ADDRESS@tcp:/FILESYSTEM`.
  public var mountPoint: Swift.String = Swift.String()

  /// Output only. Timestamp when the instance was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Timestamp when the instance was last updated.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Optional. A user-readable description of the instance.
  public var description: Swift.String = Swift.String()

  /// Optional. Labels as key value pairs.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Required. The throughput of the instance in MB/s/TiB.
  /// Valid values are 125, 250, 500, 1000.
  public var perUnitStorageThroughput: Swift.Int64 = Swift.Int64()

  /// Optional. Indicates whether you want to enable support for GKE clients. By
  /// default, GKE clients are not supported. Deprecated. No longer required for
  /// GKE instance creation.
  @available(*, deprecated)
  public var gkeSupportEnabled: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `Instance`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Instance().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The possible states of an instance.
  public enum State: Codable, Equatable, Sendable {
    /// Not set.
    case unspecified
    /// The instance is available for use.
    case active
    /// The instance is being created and is not yet ready for use.
    case creating
    /// The instance is being deleted.
    case deleting
    /// The instance is being upgraded.
    case upgrading
    /// The instance is being repaired.
    case repairing
    /// The instance is stopped.
    case stopped
    /// The instance is being updated.
    case updating
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .active: return 1
      case .creating: return 2
      case .deleting: return 3
      case .upgrading: return 4
      case .repairing: return 5
      case .stopped: return 6
      case .updating: return 7
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .active: return "ACTIVE"
      case .creating: return "CREATING"
      case .deleting: return "DELETING"
      case .upgrading: return "UPGRADING"
      case .repairing: return "REPAIRING"
      case .stopped: return "STOPPED"
      case .updating: return "UPDATING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "ACTIVE": self = .active
      case "CREATING": self = .creating
      case "DELETING": self = .deleting
      case "UPGRADING": self = .upgrading
      case "REPAIRING": self = .repairing
      case "STOPPED": self = .stopped
      case "UPDATING": self = .updating
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .active
      case 2: self = .creating
      case 3: self = .deleting
      case 4: self = .upgrading
      case 5: self = .repairing
      case 6: self = .stopped
      case 7: self = .updating
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .active: return try container.encode(1)
      case .creating: return try container.encode(2)
      case .deleting: return try container.encode(3)
      case .upgrading: return try container.encode(4)
      case .repairing: return try container.encode(5)
      case .stopped: return try container.encode(6)
      case .updating: return try container.encode(7)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.lustre.v1.Instance"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
