// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLocation
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax

extension Clients {
  protocol LustreStub: Sendable {
    func listInstances(
      request: ListInstancesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLustreV1.ListInstancesResponse

    func getInstance(
      request: GetInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLustreV1.Instance

    func createInstance(
      request: CreateInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateInstance(
      request: UpdateInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteInstance(
      request: DeleteInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func rescheduleMaintenance(
      request: RescheduleMaintenanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func importData(
      request: ImportDataRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func exportData(
      request: ExportDataRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func createMirror(
      request: CreateMirrorRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateMirror(
      request: UpdateMirrorRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteMirror(
      request: DeleteMirrorRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getMirror(
      request: GetMirrorRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLustreV1.Mirror

    func listMirrors(
      request: ListMirrorsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLustreV1.ListMirrorsResponse

    func createDirectoryPolicy(
      request: CreateDirectoryPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteDirectoryPolicy(
      request: DeleteDirectoryPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getDirectoryPolicy(
      request: GetDirectoryPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLustreV1.DirectoryPolicy

    func listDirectoryPolicies(
      request: ListDirectoryPoliciesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLustreV1.ListDirectoryPoliciesResponse

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}
