// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleCloudLocation
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleWKT
@_spi(GoogleCloudInternal) public import GoogleGax

/// Service describing handlers for resources
///
/// @Snippet(path: "LustreQuickstart")
public final class LustreClient: Clients.LustreProtocol, Sendable {
  let inner: any Clients.LustreStub
  let pollingErrorPolicy: GoogleGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleGax.BackoffPolicy

  /// Creates a new `LustreClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.LustreStub = try Clients.LustreTransport(options)
    inner = Clients.LustreRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.LustreLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Lists instances in a given project and location.
  ///
  /// @Snippet(path: "Lustre_ListInstances")
  public func listInstances(
    request: ListInstancesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLustreV1.ListInstancesResponse {
    try await self.inner.listInstances(request: request, options: options)
  }

  /// Gets details of a single instance.
  ///
  /// @Snippet(path: "Lustre_GetInstance")
  public func getInstance(
    request: GetInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLustreV1.Instance {
    try await self.inner.getInstance(request: request, options: options)
  }

  /// Creates a new instance in a given project and location.
  ///
  /// @Snippet(path: "Lustre_CreateInstance")
  public func createInstance(
    request: CreateInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createInstance(request: request, options: options)
  }

  /// Creates a new instance in a given project and location.
  ///
  /// @Snippet(path: "Lustre_CreateInstance")
  public func createInstancePollingUntilDone(
    request: CreateInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Instance>.State
      in
      return try op._extractStatus(Instance.self)
    }
    let rawOp = try await self.createInstance(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Instance>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates the parameters of a single instance.
  ///
  /// @Snippet(path: "Lustre_UpdateInstance")
  public func updateInstance(
    request: UpdateInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateInstance(request: request, options: options)
  }

  /// Updates the parameters of a single instance.
  ///
  /// @Snippet(path: "Lustre_UpdateInstance")
  public func updateInstancePollingUntilDone(
    request: UpdateInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Instance>.State
      in
      return try op._extractStatus(Instance.self)
    }
    let rawOp = try await self.updateInstance(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Instance>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a single instance.
  ///
  /// @Snippet(path: "Lustre_DeleteInstance")
  public func deleteInstance(
    request: DeleteInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteInstance(request: request, options: options)
  }

  /// Deletes a single instance.
  ///
  /// @Snippet(path: "Lustre_DeleteInstance")
  public func deleteInstancePollingUntilDone(
    request: DeleteInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State
      in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteInstance(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Imports data from Cloud Storage to a Managed Lustre instance.
  ///
  /// @Snippet(path: "Lustre_ImportData")
  public func importData(
    request: ImportDataRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.importData(request: request, options: options)
  }

  /// Imports data from Cloud Storage to a Managed Lustre instance.
  ///
  /// @Snippet(path: "Lustre_ImportData")
  public func importDataPollingUntilDone(
    request: ImportDataRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<ImportDataResponse> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<ImportDataResponse>.State in
      return try op._extractStatus(ImportDataResponse.self)
    }
    let rawOp = try await self.importData(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<ImportDataResponse>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Exports data from a Managed Lustre instance to Cloud Storage.
  ///
  /// @Snippet(path: "Lustre_ExportData")
  public func exportData(
    request: ExportDataRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.exportData(request: request, options: options)
  }

  /// Exports data from a Managed Lustre instance to Cloud Storage.
  ///
  /// @Snippet(path: "Lustre_ExportData")
  public func exportDataPollingUntilDone(
    request: ExportDataRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<ExportDataResponse> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<ExportDataResponse>.State in
      return try op._extractStatus(ExportDataResponse.self)
    }
    let rawOp = try await self.exportData(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<ExportDataResponse>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "Lustre_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "Lustre_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Lustre_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Lustre_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Lustre_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Lustre_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `LustreClient`.
  ///
  /// To mock `LustreClient` change your functions to receive
  /// `some LustreProtocol` or `any LustreProtocol`
  /// and pass a mock implementation in your tests.
  public protocol LustreProtocol: Sendable {
    /// See `LustreClient.createInstance`.
    func createInstancePollingUntilDone(request: CreateInstanceRequest) async throws
      -> any GoogleGax.PollableOperation<Instance>

    /// See `LustreClient.createInstance`.
    func createInstancePollingUntilDone(
      parent: Swift.String,
      instance: Instance?,
      instanceId: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Instance>

    /// See `LustreClient.updateInstance`.
    func updateInstancePollingUntilDone(request: UpdateInstanceRequest) async throws
      -> any GoogleGax.PollableOperation<Instance>

    /// See `LustreClient.updateInstance`.
    func updateInstancePollingUntilDone(
      instance: Instance?,
      updateMask: GoogleWKT.WKTFieldMask?,
    ) async throws -> any GoogleGax.PollableOperation<Instance>

    /// See `LustreClient.deleteInstance`.
    func deleteInstancePollingUntilDone(request: DeleteInstanceRequest) async throws
      -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `LustreClient.deleteInstance`.
    func deleteInstancePollingUntilDone(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `LustreClient.importData`.
    func importDataPollingUntilDone(request: ImportDataRequest) async throws -> any GoogleGax
      .PollableOperation<ImportDataResponse>

    /// See `LustreClient.importData`.
    func importDataPollingUntilDone(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<ImportDataResponse>

    /// See `LustreClient.exportData`.
    func exportDataPollingUntilDone(request: ExportDataRequest) async throws -> any GoogleGax
      .PollableOperation<ExportDataResponse>

    /// See `LustreClient.listInstances`.
    func listInstances(
      request: ListInstancesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLustreV1.ListInstancesResponse

    /// See `LustreClient.getInstance`.
    func getInstance(
      request: GetInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLustreV1.Instance

    /// See `LustreClient.createInstance`.
    func createInstance(
      request: CreateInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `LustreClient.createInstance`.
    func createInstancePollingUntilDone(
      request: CreateInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Instance>

    /// See `LustreClient.updateInstance`.
    func updateInstance(
      request: UpdateInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `LustreClient.updateInstance`.
    func updateInstancePollingUntilDone(
      request: UpdateInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Instance>

    /// See `LustreClient.deleteInstance`.
    func deleteInstance(
      request: DeleteInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `LustreClient.deleteInstance`.
    func deleteInstancePollingUntilDone(
      request: DeleteInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `LustreClient.importData`.
    func importData(
      request: ImportDataRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `LustreClient.importData`.
    func importDataPollingUntilDone(
      request: ImportDataRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<ImportDataResponse>

    /// See `LustreClient.exportData`.
    func exportData(
      request: ExportDataRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `LustreClient.exportData`.
    func exportDataPollingUntilDone(
      request: ExportDataRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<ExportDataResponse>

    /// See `LustreClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `LustreClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `LustreClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `LustreClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `LustreClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.LustreProtocol {
  public func listInstances(request: ListInstancesRequest) async throws
    -> GoogleCloudLustreV1.ListInstancesResponse
  {
    try await self.listInstances(request: request, options: .init())
  }

  public func listInstances(
    request: ListInstancesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLustreV1.ListInstancesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listInstancesByItems(
    request: ListInstancesRequest
  ) -> any AsyncSequence<Instance, Swift.Error> {
    self.listInstancesByItems(request: request, options: .init())
  }

  /// Lists instances in a given project and location.
  ///
  /// @Snippet(path: "Lustre_ListInstances")
  public func listInstancesByItems(
    request: ListInstancesRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Instance, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLustreV1.ListInstancesResponse in
      var request = request
      request.pageToken = token
      return try await self.listInstances(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listInstancesByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<Instance, Swift.Error> {
    let request = ListInstancesRequest().with {
      $0.parent = parent
    }
    return self.listInstancesByItems(request: request)
  }

  public func getInstance(request: GetInstanceRequest) async throws -> GoogleCloudLustreV1.Instance
  {
    try await self.getInstance(request: request, options: .init())
  }

  public func getInstance(
    request: GetInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLustreV1.Instance {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getInstance(
    name: Swift.String,
  ) async throws -> GoogleCloudLustreV1.Instance {
    let request = GetInstanceRequest().with {
      $0.name = name
    }
    return try await self.getInstance(request: request)
  }

  public func createInstance(request: CreateInstanceRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createInstance(request: request, options: .init())
  }

  public func createInstance(
    request: CreateInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createInstancePollingUntilDone(request: CreateInstanceRequest) async throws
    -> any GoogleGax.PollableOperation<Instance>
  {
    try await self.createInstancePollingUntilDone(request: request, options: .init())
  }

  public func createInstancePollingUntilDone(
    request: CreateInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Instance>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createInstancePollingUntilDone(
    parent: Swift.String,
    instance: Instance?,
    instanceId: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let request = CreateInstanceRequest().with {
      $0.parent = parent
      $0.instance = instance
      $0.instanceId = instanceId
    }
    return try await self.createInstancePollingUntilDone(request: request)
  }

  public func updateInstance(request: UpdateInstanceRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateInstance(request: request, options: .init())
  }

  public func updateInstance(
    request: UpdateInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateInstancePollingUntilDone(request: UpdateInstanceRequest) async throws
    -> any GoogleGax.PollableOperation<Instance>
  {
    try await self.updateInstancePollingUntilDone(request: request, options: .init())
  }

  public func updateInstancePollingUntilDone(
    request: UpdateInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Instance>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateInstancePollingUntilDone(
    instance: Instance?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<Instance> {
    let request = UpdateInstanceRequest().with {
      $0.instance = instance
      $0.updateMask = updateMask
    }
    return try await self.updateInstancePollingUntilDone(request: request)
  }

  public func deleteInstance(request: DeleteInstanceRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteInstance(request: request, options: .init())
  }

  public func deleteInstance(
    request: DeleteInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteInstancePollingUntilDone(request: DeleteInstanceRequest) async throws
    -> any GoogleGax.PollableOperation<Swift.Void>
  {
    try await self.deleteInstancePollingUntilDone(request: request, options: .init())
  }

  public func deleteInstancePollingUntilDone(
    request: DeleteInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteInstancePollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteInstanceRequest().with {
      $0.name = name
    }
    return try await self.deleteInstancePollingUntilDone(request: request)
  }

  public func importData(request: ImportDataRequest) async throws -> GoogleLongRunning.Operation {
    try await self.importData(request: request, options: .init())
  }

  public func importData(
    request: ImportDataRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func importDataPollingUntilDone(request: ImportDataRequest) async throws -> any GoogleGax
    .PollableOperation<ImportDataResponse>
  {
    try await self.importDataPollingUntilDone(request: request, options: .init())
  }

  public func importDataPollingUntilDone(
    request: ImportDataRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<ImportDataResponse> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<ImportDataResponse>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func importDataPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<ImportDataResponse> {
    let request = ImportDataRequest().with {
      $0.name = name
    }
    return try await self.importDataPollingUntilDone(request: request)
  }

  public func exportData(request: ExportDataRequest) async throws -> GoogleLongRunning.Operation {
    try await self.exportData(request: request, options: .init())
  }

  public func exportData(
    request: ExportDataRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func exportDataPollingUntilDone(request: ExportDataRequest) async throws -> any GoogleGax
    .PollableOperation<ExportDataResponse>
  {
    try await self.exportDataPollingUntilDone(request: request, options: .init())
  }

  public func exportDataPollingUntilDone(
    request: ExportDataRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<ExportDataResponse> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<ExportDataResponse>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    self.listLocationsByItems(request: request, options: .init())
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "Lustre_ListLocations")
  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    self.listOperationsByItems(request: request, options: .init())
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Lustre_ListOperations")
  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperationsByItems(
    name: Swift.String,
    filter: Swift.String,
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return self.listOperationsByItems(request: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
