// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
@_spi(GoogleCloudInternal) import GoogleGax

extension Clients {
  final class LustreRetry: LustreStub {
    let inner: any LustreStub
    let options: GoogleGax.ClientOptions

    public init(_ inner: any LustreStub, options: GoogleGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func listInstances(
      request: ListInstancesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLustreV1.ListInstancesResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListInstancesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLustreV1.ListInstancesResponse
          in
          return try await self.inner.listInstances(request: r, options: o)
        })
    }

    public func getInstance(
      request: GetInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLustreV1.Instance {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetInstanceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLustreV1.Instance
          in
          return try await self.inner.getInstance(request: r, options: o)
        })
    }

    public func createInstance(
      request: CreateInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateInstanceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createInstance(request: r, options: o)
        })
    }

    public func updateInstance(
      request: UpdateInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateInstanceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateInstance(request: r, options: o)
        })
    }

    public func deleteInstance(
      request: DeleteInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteInstanceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteInstance(request: r, options: o)
        })
    }

    public func rescheduleMaintenance(
      request: RescheduleMaintenanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: RescheduleMaintenanceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.rescheduleMaintenance(request: r, options: o)
        })
    }

    public func importData(
      request: ImportDataRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: ImportDataRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.importData(request: r, options: o)
        })
    }

    public func exportData(
      request: ExportDataRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: ExportDataRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.exportData(request: r, options: o)
        })
    }

    public func createMirror(
      request: CreateMirrorRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateMirrorRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createMirror(request: r, options: o)
        })
    }

    public func updateMirror(
      request: UpdateMirrorRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateMirrorRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateMirror(request: r, options: o)
        })
    }

    public func deleteMirror(
      request: DeleteMirrorRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteMirrorRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteMirror(request: r, options: o)
        })
    }

    public func getMirror(
      request: GetMirrorRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLustreV1.Mirror {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetMirrorRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLustreV1.Mirror
          in
          return try await self.inner.getMirror(request: r, options: o)
        })
    }

    public func listMirrors(
      request: ListMirrorsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLustreV1.ListMirrorsResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListMirrorsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLustreV1.ListMirrorsResponse
          in
          return try await self.inner.listMirrors(request: r, options: o)
        })
    }

    public func createDirectoryPolicy(
      request: CreateDirectoryPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateDirectoryPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createDirectoryPolicy(request: r, options: o)
        })
    }

    public func deleteDirectoryPolicy(
      request: DeleteDirectoryPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteDirectoryPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteDirectoryPolicy(request: r, options: o)
        })
    }

    public func getDirectoryPolicy(
      request: GetDirectoryPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLustreV1.DirectoryPolicy {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetDirectoryPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLustreV1.DirectoryPolicy
          in
          return try await self.inner.getDirectoryPolicy(request: r, options: o)
        })
    }

    public func listDirectoryPolicies(
      request: ListDirectoryPoliciesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLustreV1.ListDirectoryPoliciesResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListDirectoryPoliciesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLustreV1.ListDirectoryPoliciesResponse
          in
          return try await self.inner.listDirectoryPolicies(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleIAMV1.SetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.setIamPolicy(request: r, options: o)
        })
    }

    public func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleIAMV1.GetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.getIamPolicy(request: r, options: o)
        })
    }

    public func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleIAMV1.TestIamPermissionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.TestIamPermissionsResponse
          in
          return try await self.inner.testIamPermissions(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      return try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
