// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Represents the metadata of the long-running transfer operation.
public struct TransferOperationMetadata: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The progress of the transfer operation.
  public var counters: TransferCounters? = nil

  /// Output only. The type of transfer occurring.
  public var transferType: TransferType = TransferType()

  /// Output only. Error summary about the transfer operation
  public var errorSummaries: [ErrorSummary] = []

  /// The source of transfer operation.
  public var source: OneOf_Source? = nil

  /// The destination of transfer operation.
  public var destination: OneOf_Destination? = nil

  /// Initialize a new instance of `TransferOperationMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TransferOperationMetadata().with { $0.sourceLustrePath = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case sourceLustrePath = "sourceLustrePath"
    case sourceGcsPath = "sourceGcsPath"
    case destinationGcsPath = "destinationGcsPath"
    case destinationLustrePath = "destinationLustrePath"
    case counters = "counters"
    case transferType = "transferType"
    case errorSummaries = "errorSummaries"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.counters = try container.decodeIfPresent(TransferCounters.self, forKey: .counters)
    self.transferType = try container.decode(TransferType.self, forKey: .transferType)
    self.errorSummaries = try container.decode([ErrorSummary].self, forKey: .errorSummaries)

    var source: OneOf_Source? = nil
    let sourceCheckAndSet = {
      if source != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'source'"))
      }
      source = $0
    }
    if let sourceLustrePath = try container.decodeIfPresent(
      LustrePath?.self, forKey: .sourceLustrePath)
    {
      try sourceCheckAndSet(.sourceLustrePath(sourceLustrePath))
    }
    if let sourceGcsPath = try container.decodeIfPresent(GcsPath?.self, forKey: .sourceGcsPath) {
      try sourceCheckAndSet(.sourceGcsPath(sourceGcsPath))
    }
    self.source = source

    var destination: OneOf_Destination? = nil
    let destinationCheckAndSet = {
      if destination != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'destination'"))
      }
      destination = $0
    }
    if let destinationGcsPath = try container.decodeIfPresent(
      GcsPath?.self, forKey: .destinationGcsPath)
    {
      try destinationCheckAndSet(.destinationGcsPath(destinationGcsPath))
    }
    if let destinationLustrePath = try container.decodeIfPresent(
      LustrePath?.self, forKey: .destinationLustrePath)
    {
      try destinationCheckAndSet(.destinationLustrePath(destinationLustrePath))
    }
    self.destination = destination
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.counters, forKey: .counters)
    try container.encode(self.transferType, forKey: .transferType)
    try container.encode(self.errorSummaries, forKey: .errorSummaries)

    if let choice = self.source {
      switch choice {
      case .sourceLustrePath(let value):
        try container.encode(value, forKey: .sourceLustrePath)
      case .sourceGcsPath(let value):
        try container.encode(value, forKey: .sourceGcsPath)
      }
    }

    if let choice = self.destination {
      switch choice {
      case .destinationGcsPath(let value):
        try container.encode(value, forKey: .destinationGcsPath)
      case .destinationLustrePath(let value):
        try container.encode(value, forKey: .destinationLustrePath)
      }
    }
  }

  /// The source of transfer operation.
  public enum OneOf_Source: Codable, Equatable, Sendable {
    /// Output only. Lustre source.
    indirect case sourceLustrePath(LustrePath?)
    /// Output only. Cloud Storage source.
    indirect case sourceGcsPath(GcsPath?)
  }

  /// The destination of transfer operation.
  public enum OneOf_Destination: Codable, Equatable, Sendable {
    /// Output only. Cloud Storage destination.
    indirect case destinationGcsPath(GcsPath?)
    /// Output only. Lustre destination.
    indirect case destinationLustrePath(LustrePath?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.lustre.v1.TransferOperationMetadata"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
