// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A collection of counters that report the progress of a transfer operation.
public struct TransferCounters: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Objects found in the data source that are scheduled to be transferred,
  /// excluding any that are filtered based on object conditions or skipped due
  /// to sync.
  public var foundObjectsCount: Swift.Int64 = Swift.Int64()

  /// Total number of bytes found in the data source that are scheduled to be
  /// transferred, excluding any that are filtered based on object conditions or
  /// skipped due to sync.
  public var bytesFoundCount: Swift.Int64 = Swift.Int64()

  /// Objects in the data source that are not transferred because they already
  /// exist in the data destination.
  public var objectsSkippedCount: Swift.Int64 = Swift.Int64()

  /// Bytes in the data source that are not transferred because they already
  /// exist in the data destination.
  public var bytesSkippedCount: Swift.Int64 = Swift.Int64()

  /// Objects that are copied to the data destination.
  public var objectsCopiedCount: Swift.Int64 = Swift.Int64()

  /// Bytes that are copied to the data destination.
  public var bytesCopiedCount: Swift.Int64 = Swift.Int64()

  /// Output only. Objects that are failed to write to the data destination.
  public var objectsFailedCount: Swift.Int64 = Swift.Int64()

  /// Output only. Bytes that are failed to write to the data destination.
  public var bytesFailedCount: Swift.Int64 = Swift.Int64()

  /// Initialize a new instance of `TransferCounters`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TransferCounters().with { $0.foundObjectsCount = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.lustre.v1.TransferCounters"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
